name: Min App

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - app/*

defaults:
  run:
    working-directory: app

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest index_test.py

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./app
        tags: ${{ secrets.DOCKER_USERNAME }}/blunomy-min-app:latest

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Authenticate to Google Cloud
#      uses: google-github-actions/auth@v1
#      with:
#        credentials_json: ${{secrets.GOOGLE_CREDENTIALS}}
#
#    - name: Get GKE Credentials
#      uses: 'google-github-actions/get-gke-credentials@v1'
#      with:
#        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
#        location: ${{ secrets.GCP_ZONE }}
#
#    - name: Deploy to Kubernetes
#      run: |
#        kubectl rollout restart deployment/min-app
